[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "lost-and-found-backend"